---
- hosts: was_servers
  remote_user: root
# ?¤치?? tomcat real version, 변??ë???? _ . ?????°기 ?¬ìë가?
  vars:
      ansible_python_interpreter: /usr/bin/python3          
      origin80: apache-tomcat-8.0.53
      origin85: apache-tomcat-8.5.90
      origin90: apache-tomcat-9.0.76
      origin100: apache-tomcat-10.1.9

  vars_prompt:
    - name: tomcatversion
      prompt: "tomcat version"
      private: no

# tomcat download, when?????? 변?? ?¬ì?? {{}} ë?¬ìí지 ??????
  tasks:
    - name: tomcat 8 down
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.53/bin/{{ origin80 }}.tar.gz
        dest: /tmp/tomcat.tar.gz
      when: tomcatversion == "8"

    - name: tomcat 8.5 down
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.90/bin/{{ origin85 }}.tar.gz
        dest: /tmp/tomcat.tar.gz
      when: tomcatversion == "8.5"

    - name: tomcat 9 down
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.76/bin/{{ origin90 }}.tar.gz
        dest: /tmp/tomcat.tar.gz
      when: tomcatversion == "9"

    - name: tomcat 10 down
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.9/bin/{{ origin100 }}.tar.gz
        dest: /tmp/tomcat.tar.gz
      when: tomcatversion == "10"

    - name: tomcat unarchive
      unarchive:
        src: /tmp/tomcat.tar.gz
        dest: /tmp/
        remote_src: yes

# Tomcat ?¬ìì ë ?´ë ?¤ì
    - name: tomcat etc
      shell: |
        mv /tmp/apache-tomcat-* /usr/local/tomcat
        useradd -d /opt/tomcat -s /bin/nologin tomcat
        chown -R tomcat:tomcat /usr/local/tomcat/ 
        rm -rf /tmp/apache-tomcat-* /tmp/tomcat*

# Tomcat AJP ???±í        
    - name: tomcat 8 config
      shell:  
        sed -i "s/redirectPort="8443"/redirectPort="8443" address="0.0.0.0" secretRequired="false"/g" /usr/local/tomcat/conf/server.xml
      when: tomcatversion == "8"

    - name: tomcat 8.5onfig
      shell:        
        sed -i '122i <Connector protocol="AJP/1.3" address="0.0.0.0" port="8009" redirectPort="8443" secretRequired="false" /> ' /usr/local/tomcat/conf/server.xml
      when: tomcatversion == "8.5"

    - name: tomcat 9 config
      shell:
        sed -i '121i <Connector protocol="AJP/1.3" address="0.0.0.0" port="8009" redirectPort="8443" secretRequired="false" /> ' /usr/local/tomcat/conf/server.xml
      when: tomcatversion == "9"

    - name: tomcat 10 config
      shell:
        sed -i '103i <Connector protocol="AJP/1.3" address="0.0.0.0" port="8009" redirectPort="8443" secretRequired="false" /> ' /usr/local/tomcat/conf/server.xml
      when: tomcatversion == "10"

    - name: tomcat log
      shell:
        cmd: |
          cat <<EOF >> /etc/logrotate.conf
          /usr/local//tomcat/logs/*.log {
              weekly
              rotate 3
              nodateext
              compress
          }

          /usr/local/tomcat/logs/catalina.out {
              weekly
              rotate 3
              dateext
              compress
          }
          EOF
         
